# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clinar < Formula
  desc "This tool can cleanup stale gitlab runners."
  homepage "https://github.com/steffakasid/clinar"
  version "0.30"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/clinar/releases/download/v0.30/clinar_0.30_darwin_amd64.tar.gz"
      sha256 "ca053ffe50d2c6bef4242861634fd182badb4f060c6e0a7bad22099793df8aa6"

      def install
        bin.install "clinar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/clinar/releases/download/v0.30/clinar_0.30_darwin_arm64.tar.gz"
      sha256 "74965f1e463ecb4dad9062c0eb9ab97f9d63aa26d74f3c18eadad87e45902442"

      def install
        bin.install "clinar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/clinar/releases/download/v0.30/clinar_0.30_linux_amd64.tar.gz"
      sha256 "43e3c1a068ce3580918f31c70365e67b7f3d555b9de39a04fe2446e2b0858472"
      def install
        bin.install "clinar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/clinar/releases/download/v0.30/clinar_0.30_linux_arm64.tar.gz"
      sha256 "ba79dea1b65bf28a36c60e21ed3c55148e33590daf1f5997011f769c61e565c2"
      def install
        bin.install "clinar"
      end
    end
  end
end
